baseurl = "/"
languageCode = "en-us"
title = "Alexander Danvers' website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "CV"
    url = "/CV.pdf"
[[menu.main]]
    name = "About"
    url = "/about_alex"
[[menu.main]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=4yKO1eUAAAAJ&hl=en"
[[menu.main]]
    name = "Psychology Today blog"
    url = "https://www.psychologytoday.com/us/blog/how-do-you-know"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/adanvers"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/alex_danvers"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "waddington_landscape.png"
    width = 100
    height = 100
    alt = "Logo"
